### ISSUE TITLE
.spec file location

### ISSUE THREAD

**Issue by lathonez** [BugsBunnyBR/ionic2-app-base#1]
As discussed, probably best to be with the source code as per the [style guide](https://github.com/mgechev/angular2-style-guide#testing)

If the angular2 community has agreed this is what we should be doing then I don't see a need to implement a path variable solution.

However we could briefly document the config changes required to make the switch

**Comment by BugsBunnyBR** [comment]
Once we have the standard way working, I can give it a try and document it.

**Comment by lathonez** [comment]
Standard way being the files together?

**Comment by BugsBunnyBR** [comment]
yes.
