### ISSUE TITLE
use webpack instead of gulp

### ISSUE THREAD

**Issue by lathonez** [BugsBunnyBR/ionic2-app-base#2]
Not sure how this would work at all, but as Ionic 2 isn't using Gulp anymore it would be great to remove that dependency

[http://stackoverflow.com/questions/35290176/executing-typescript-jasmine-tests-via-webpack-terminal-to-test-angular2](http://stackoverflow.com/questions/35290176/executing-typescript-jasmine-tests-via-webpack-terminal-to-test-angular2)

**Comment by BugsBunnyBR** [comment]
Asked mike in the slack channel...

juliocbcotta [7:14 PM] 
How is the build system of ionic2? I mean..is does not seems to use gulp...

mike [7:16 PM] 
it's using webpack to handle it

[7:16] 
and the cli to orchestrate it

juliocbcotta [7:16 PM] 
is it possible to call tasks on it from an external task or plug new tasks?

mike [7:17 PM] 
it is, it's a bit rough right now, but we're cleaning that up

[7:17] 
so I'd hold off for now

juliocbcotta [7:18 PM] 
is there a place where I can get a taste of it? just to see how things work today?

mike [7:19 PM] 
checkout the ionic.config.js file

[7:19] 
 ```  // hooks execute before or after all project-related Ionic commands
  // (so not for start, docs, but serve, run, etc.) and take in the arguments
  // passed to the command as a parameter
  //
  // The format is 'before' or 'after' + commandName (uppercased)
  // ex: beforeServe, afterRun, beforePrepare, etc.
  hooks: {
    beforeServe: function(argv) {
      //console.log('beforeServe');
    }
  }
```

[7:19] 
it can take any node process

juliocbcotta [7:21 PM] 
thanks

**Comment by BugsBunnyBR** [comment]
Do you want to wait or give it a try ?

**Comment by lathonez** [comment]
I'd say get it up and running the way we know works, on latest / we're happy with the setup. Then look at migrating to webpack.

Maybe duplicating work a bit but I dont wanna bite off too much.

Leave this open basically and we'll do it ASAP.

**Comment by BugsBunnyBR** [comment]
great, lets make it work, when the ionic team make the hooks something public/stable we can give it a try.
The sad thing is to keep both build configs...

**Comment by lathonez** [comment]
Seems like Ionic are coming back to Gulp. We should either close this / or not pursue it at least until we know what's going on.
