### ISSUE TITLE
branch with current clicker configs

### ISSUE THREAD

**Issue by BugsBunnyBR** [BugsBunnyBR/ionic2-app-base#5]
@lathonez,
I created [this](https://github.com/BugsBunnyBR/ionic2-app-base/tree/testing-support-for-ts) branch based on current clicker configs.
The problem is, app-base has no source code, so to test the changes made in this branch I created [another](https://github.com/BugsBunnyBR/ionic2-app-base/tree/testing-the-test-support) with just one test and the configs. Not very practical... but I lack a better idea.

**Comment by lathonez** [comment]
I understand why you branched off to add the source code to drive the tests, but not for the configs? Why not add the configs directly onto this fork?

Re the lack of source code, maybe this is why Tim suggested the conference app. As long as we can demonstrate it's working (by your second branch), I guess it doesn't matter?

**Comment by BugsBunnyBR** [comment]
You mean... I could have pushed the code of the first branch directly to master? I just wanted to be sure of that configs will be the one used.

yeah, I also think that is the case...add the testing config to conference-app. So, migrate it to conference-app? Wait until it is more flexible?

**Comment by lathonez** [comment]
As he suggested it and we're already running into problems I'd migrate to the conference. Your solution of having the branch for testing works though so it's your call.

Pain in the ass to fork and migrate all these issues.. Maybe wait till this stuff is stable and we're happy with it, then could move to conference and add more tests?

**Comment by BugsBunnyBR** [comment]
lets wait. When we have something more flexible and 'ready to show' we fork conference-app.
Humm, lets keep the development into clicker or would you like to keep each project one separated?

**Comment by lathonez** [comment]
happy to keep it centralised.
